/*:
 # Cyclical figurate numbers
 [Problem 61](https://projecteuler.net/problem=61) - Diifculty level: 20%

 Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and are generated by the following formulae:

 ![](61-1.png)

 The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.

 1. The set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).
 2. Each polygonal type: triangle (P(3,127)=8128), square (P(4,91)=8281), and pentagonal (P(5,44)=2882), is represented by a different number in the set.
 3. This is the only set of 4-digit numbers with this property.
 
 Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different number in the set.
 */
