/*:
 # Triangular, pentagonal, and hexagonal
 [Problem 45](https://projecteuler.net/problem=45) - Diifculty level: 5%

 Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

 ![](45-1.png)

 It can be verified that T(285) = P(165) = H(143) = 40755.

 Find the next triangle number that is also pentagonal and hexagonal.
 */
